#!/usr/bin/env ruby

require "optparse"
require "json"

# For pull_request triggers, the GITHUB_SHA and GITHUB_REF environment variables
# point to a temporary merge commit SHA and branch name, instead of
# the source branch and its head commit SHA.
# For more details, see: https://github.com/orgs/community/discussions/26325

# Here, we are fetching the pull request env vars differently, so that
# the behavior of the action stays consistent across all event types.
event_path = File.read(ENV["GITHUB_EVENT_PATH"])
event_payload = JSON.parse(event_path)

github_sha = if ENV["GITHUB_EVENT_NAME"] == "pull_request"
  event_payload.dig("pull_request", "head", "sha")
else
  ENV["GITHUB_SHA"]
end

github_ref = if ENV["GITHUB_EVENT_NAME"] == "pull_request"
  event_payload.dig("pull_request", "head", "ref")
else
  ENV["GITHUB_REF"].sub("refs/heads/", "")
end

puts "Current SHA: #{github_sha}"
puts "Current Ref: #{github_ref}"

options = {
  slices: [],
  sha: github_sha,
  branch: github_ref,
}

OptionParser.new do |opts|
  opts.banner = "Usage: verify [options]"

  opts.on("-s", "--slices [SLICES]", Array) do |v|
    options[:slices] = v.sort
  end

  opts.on("-c", "--commit-sha [SHA]", String) do |v|
    options[:sha] = v
  end

  opts.on("-b", "--branch-name [BRANCH]", String) do |v|
    options[:branch] = v
  end
end.parse!

cmd = <<-CMD
aws dynamodb get-item --endpoint-url #{ENV["AWS_ENDPOINT_URL"]} \
                      --table-name metadata \
                      --region local \
                      --key '{"repository":{"S":"#{ENV["GITHUB_REPOSITORY"]}"},"commit_sha":{"S":"#{options[:sha]}"}}'
CMD

result = `#{cmd.strip}`.strip

raise "Missing entry in DynamoDB" if result.empty?

item = JSON.parse(result)

puts "Found item:", JSON.pretty_generate(item)

slices = item.dig("Item", "slices", "L")&.map { |s| s["S"] } || []

raise "Wrong slices in DynamoDB, expected: #{options[:slices].inspect}, got: #{slices.inspect}" if slices.sort != options[:slices]

unless options[:branch].empty?
  branch = item.dig("Item", "commit_branch", "S")

  raise "Wrong branch in DynamoDB, expected: #{options[:branch].inspect}, got: #{branch.inspect}" if branch != options[:branch]
end

puts "All good!"
