name: 'Publish build metadata'
description: 'Collects build artifacts metadata and publishes them to DynamoDB'

inputs:
  access_key_id:
    description: 'AWS_ACCESS_KEY_ID'
    required: false
    default: null
  secret_access_key:
    description: 'AWS_SECRET_ACCESS_KEY'
    required: false
    default: null
  meta_table_arn:
    description: 'DynamoDB metadata table ARN'
    required: true
  slices:
    description: 'Microverse slice names'
    required: false
    default: null
  sha:
    description: 'Optional custom commit SHA that should override `GITHUB_SHA` environment variable'
    required: false
    default: null
  branch:
    description: 'Optional custom branch name that should override `GITHUB_REF` environment variable'
    required: false
    default: null
  commit_message_sha:
    description: 'Optional custom commit SHA of the commit message that should be displayed in the Deploy App UI'
    required: false
    default: null

runs:
  using: 'node20'
  main: 'dist/index.js'
