name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

env:
  AWS_ACCESS_KEY_ID: aws-access-key-id
  AWS_SECRET_ACCESS_KEY: aws-secret-access-key

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Boot up DynamoDB
        run: docker-compose up -d

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - run: npm ci

      - run: make test
        env:
          DEBUG: 'true'

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest

    env:
      AWS_ENDPOINT_URL: 'http://localhost:8000'
      ACTIONS_RUNNER_DEBUG: true
      DEBUG: 'true'

    steps:
      - uses: actions/checkout@v2

      - name: Boot up DynamoDB
        run: docker-compose up -d

      - name: Prep metadata table
        env:
          AWS_ACCESS_KEY_ID: 'aws-access-key-id'
          AWS_SECRET_ACCESS_KEY: 'aws-secret-access-key'
        run: |
          aws dynamodb create-table \
                       --endpoint-url $AWS_ENDPOINT_URL \
                       --region local \
                       --table-name metadata \
                       --attribute-definitions \
                         AttributeName=repository,AttributeType=S \
                         AttributeName=commit_sha,AttributeType=S \
                       --key-schema \
                         AttributeName=repository,KeyType=HASH \
                         AttributeName=commit_sha,KeyType=RANGE \
                       --provisioned-throughput \
                         ReadCapacityUnits=1,WriteCapacityUnits=1

      - name: Test with given slices
        uses: ./
        with:
          access_key_id: 'aws-access-key-id'
          secret_access_key: 'aws-secret-access-key'
          meta_table_arn: 'arn:aws:dynamodb:local:000000000000:table/metadata'
          slices: 'api,consumer'

      - name: Check if everything is there
        env:
          AWS_ACCESS_KEY_ID: 'aws-access-key-id'
          AWS_SECRET_ACCESS_KEY: 'aws-secret-access-key'
        run: ./.github/scripts/verify --slices api,consumer

      - name: Test without slices
        uses: ./
        with:
          access_key_id: 'aws-access-key-id'
          secret_access_key: 'aws-secret-access-key'
          meta_table_arn: 'arn:aws:dynamodb:local:000000000000:table/metadata'

      - name: Check if everything is there
        env:
          AWS_ACCESS_KEY_ID: 'aws-access-key-id'
          AWS_SECRET_ACCESS_KEY: 'aws-secret-access-key'
        run: ./.github/scripts/verify

      - name: Test with custom branch name
        uses: ./
        with:
          access_key_id: 'aws-access-key-id'
          secret_access_key: 'aws-secret-access-key'
          meta_table_arn: 'arn:aws:dynamodb:local:000000000000:table/metadata'
          branch: 'feature/add-examples'

      - name: Check if everything is there
        env:
          AWS_ACCESS_KEY_ID: 'aws-access-key-id'
          AWS_SECRET_ACCESS_KEY: 'aws-secret-access-key'
        run: ./.github/scripts/verify --branch-name feature/add-examples
