name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

env:
  AWS_ACCESS_KEY_ID: TestAccessKeyID
  AWS_SECRET_ACCESS_KEY: TestSecretAccessKey

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Boot up DynamoDB
        run: docker-compose up -d

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - run: npm ci

      - run: make test
        env:
          DEBUG: 'true'

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest

    env:
      AWS_ENDPOINT_URL: 'http://localhost:8000'
      ACTIONS_RUNNER_DEBUG: true
      DEBUG: 'true'

    steps:
      - uses: actions/checkout@v3

      - name: Boot up DynamoDB
        run: docker-compose up -d

      - name: Prep metadata table
        env:
          AWS_ACCESS_KEY_ID: TestAccessKeyID
          AWS_SECRET_ACCESS_KEY: TestSecretAccessKey
        run: |
          aws dynamodb create-table \
                       --endpoint-url $AWS_ENDPOINT_URL \
                       --region local \
                       --table-name metadata \
                       --attribute-definitions \
                         AttributeName=repository,AttributeType=S \
                         AttributeName=commit_sha,AttributeType=S \
                       --key-schema \
                         AttributeName=repository,KeyType=HASH \
                         AttributeName=commit_sha,KeyType=RANGE \
                       --provisioned-throughput \
                         ReadCapacityUnits=1,WriteCapacityUnits=1

      - name: Test with given slices
        uses: ./
        with:
          access_key_id: TestAccessKeyID
          secret_access_key: TestSecretAccessKey
          meta_table_arn: 'arn:aws:dynamodb:local:000000000000:table/metadata'
          slices: 'api,consumer'

      - name: Check if everything is there
        env:
          AWS_ACCESS_KEY_ID: TestAccessKeyID
          AWS_SECRET_ACCESS_KEY: TestSecretAccessKey
        run: ./.github/scripts/verify --slices api,consumer

      - name: Test without slices
        uses: ./
        with:
          access_key_id: TestAccessKeyID
          secret_access_key: TestSecretAccessKey
          meta_table_arn: 'arn:aws:dynamodb:local:000000000000:table/metadata'

      - name: Check if everything is there
        env:
          AWS_ACCESS_KEY_ID: TestAccessKeyID
          AWS_SECRET_ACCESS_KEY: TestSecretAccessKey
        run: ./.github/scripts/verify

      - name: Test with custom branch name
        uses: ./
        with:
          access_key_id: TestAccessKeyID
          secret_access_key: TestSecretAccessKey
          meta_table_arn: 'arn:aws:dynamodb:local:000000000000:table/metadata'
          branch: 'feature/add-examples'

      - name: Check if everything is there
        env:
          AWS_ACCESS_KEY_ID: TestAccessKeyID
          AWS_SECRET_ACCESS_KEY: TestSecretAccessKey
        run: ./.github/scripts/verify --branch-name feature/add-examples

  release:
    needs: [units, test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
